name: back

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and test with Maven
        run: |
          mvn -B package 
          mvn -B test
        working-directory: ./back/

      - name: Generate back report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Back-report
          path: back/target/site/jacoco/

  quality:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4

      - name: Download Back Report
        uses: actions/download-artifact@v4
        with:
          name: Back-report
          path: ./back/target/site/jacoco/

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build backend with Maven
        run: cd back && mvn clean install

      - name: SonarCloud Scan
        uses: sonarSource/sonarcloud-github-action@master
        with:
          args:
            -Dproject.settings=back/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}

  deployment:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build back-end
        run: |
          cd back
          mvn clean install 

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for back-end
        uses: docker/build-push-action@v2
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest
