name: Backend CI/CD

on:
  push:
    branches: [develop]
    paths:
      - 'back/**'
  pull_request:
    branches: [develop]
    paths:
      - 'back/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Install backend dependencies
        run: mvn clean install

      - name: Execute tests
        run: mvn test

      - name: Creation of the Jacoco code coverage report
        run: mvn jacoco:report

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCo code coverage
          path: ./back/target/site/jacoco/

  sonar:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Install backend dependencies
        run: mvn clean install

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar

  docker:
    runs-on: ubuntu-latest
    needs: sonar
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t bobapp-back .
          docker tag bobapp-back ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest
