name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    strategy:
      matrix:
        java-version: [11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Install backend dependencies
        run: mvn clean install

      - name: Execute tests
        run: mvn clean test

      - name: Creation of the Jacoco code coverage report
        run: mvn jacoco:report

      - name: Backend code coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCo code coverage
          path: ./back/target/site/jacoco/

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/front

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: |
          npm ci

      - name: Build and execute tests
        run: |
          npm run build --if-present
          npm run test:prod

      - name: Frontend code coverage report artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Jest code coverage
          path: ./front/coverage/bobapp