name: front

on:
  push:
    branches: [ "main" ]
    paths:
      - "front/**"
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'

      - run: npm ci
        working-directory: ./front/

      - name: run test and generate code coverage
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: ./front/

      - name: Generate front report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Front-report
          path: front/coverage

  quality:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --all

      - name: Download Front Report
        uses: actions/download-artifact@v4
        with:
          name: Front-report
          path: ./front/coverage/bobapp

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        with:
          args: -Dproject.settings=front/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
